### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by Poncherelly** [meraki/alexa-skill#1]
Hello and I was browsing YouTube and found this link https://www.youtube.com/watch?v=tRd5xxyQQrY.  I thought this was amazing and of course wanted to implement it.  Since there was no direction provided on YouTube, I googled it and came across GitHub which seems to be the code behind the project.  If this is right, I'm one step closer to implementing however I need  a little help if you or someone doesn't mind.

I found this how to https://www.youtube.com/watch?v=n_hMTi1VKWQ&feature=youtu.be on how to create a skill but when I try and merge the two information sources I get hung up on the code.  Seems that the skills how to is dealing with Json script and this is dealing with Python.  I know I'm missing a step but can't for the life of me figure that next pr previous step out.

If anyone could provide a more basic level of how to I would be very grateful.

thank you in advance.

Ponch

**Comment by shiyuechengineer** [comment]
Hi Ponch, I'm the one who recorded that video and am in the process of releasing an updated API guide/Alexa document for the Meraki Dashboard API. Will add to the thread here shortly by the end of next week with these updates!

**Comment by Poncherelly** [comment]
That's great and thank you. Most of all, thanks for the cool Alexa add on!  

I'm really looking forward to implementing it.

**Comment by Poncherelly** [comment]
Any progress?  If not, I won't bug you until after the holidays. If yes, so looking forward to trying ;)

Happy holidays non the less.

**Comment by shiyuechengineer** [comment]
Sorry this took so long, but finally finished writing up the [Dashboard API & Amazon Alexa setup guide](https://www.dropbox.com/s/dly4yx9u35qwsyk/Dashboard%20API%20-%20Amazon%20Alexa%2C%20Setup%20Guide.pptx?dl=0). Please let me know if you have any questions, and have fun!

**Comment by Poncherelly** [comment]
Just saw your PPTX document and it looks great.  I'm going to give this a try over the next couple of days to see if I can follow well enough 😊
Thanks again for this ... it looks cool and will impress my tech friends and annoy my wife nicely 😉.


________________________________
